<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mi Página Web</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            margin: 50px;
        }
        h1 {
            color: #007bff;
        }
        p {
            font-size: 18px;
        }
    </style>
</head>
<body>
    <h1>Bienvenido a Mi Página Web</h1>
    <p>Esta es una página sencilla creada con HTML y un poco de CSS.</p>
    <a href="https://www.example.com">Visita nuestro sitio</a>
</body>
</html>
